<ouc:editor wysiwyg="yes"/>
<!-- <?php $year = (new DateTime("NOW", new DateTimeZone("America/New_York")))->format("Y"); ?> -->

<div class="container">
	<nav id="footer-nav-wrapper" role="navigation">
		<ul class="menu nav">
			<li class="first leaf"><a href="/">Home</a></li>
			<li class="leaf"><a href="http://www.uga.edu/">UGA</a></li>
			<li class="leaf"><a href="http://eits.uga.edu/">EITS Home</a></li>
			<li class="leaf"><a href="http://eitshelpdesk.uga.edu">EITS Help Desk</a></li>
			<li class="leaf"><a href="/contact/">Contact Us</a></li>
		</ul>
	</nav>
</div>
<div id="block-block-2">
	<section class="block block-block container">
		<p>&copy; <?php echo $year; ?> Enterprise Information Technology Services.</p>
		<p>101 Cedar Street Athens, Georgia 30602 | (706) 542-3106  |  University of Georgia. All rights reserved.</p>
	</section>
</div>