<ouc:editor wysiwyg="no"/>
<ul>
	<li class="title">About UGA</li>
	<li><a href="http://visit.uga.edu/">Visit UGA</a></li>
	<li><a href="https://ovpi.uga.edu/about-ovpi/ovpi-units/extended-campuses">Extended Campuses</a></li>
	<li><a href="http://www.architects.uga.edu/maps/current">Campus Map</a></li>
	<li><a href="http://calendar.uga.edu/">Master Calendar</a></li>
	<li><a href="http://www.hr.uga.edu/employees/employment">Employment</a></li>
</ul>
<ul>
	<li class="title">Helpful Links</li>
	<li><a href="https://my.uga.edu">MyUGA</a></li>
	<li><a href="https://oasisweb.uga.edu/">Oasis</a></li>
	<li><a href="https://www.elc.uga.edu/">eLearning Commons</a></li>
	<li><a href="http://www.bulletin.uga.edu/">UGA Bulletin</a></li>
	<li><a href="http://www.reg.uga.edu/calendars">Academic Calendars</a></li>
</ul>
<ul>
	<li class="title">Student Life</li>
	<li><a href="http://ugamail.uga.edu/">UGA Mail</a></li>
	<li><a href="http://foodservice.uga.edu/">Food Services</a></li>
	<li><a href="http://dos.uga.edu/">Campus Life</a></li>
	<li><a href="http://www.recsports.uga.edu/">Recreational Sports</a></li>
	<li><a href="https://studentacct.uga.edu">Student Accounts</a></li>
</ul>
<ul>
	<li class="title">Helpful Links</li>
	<li><a href="http://osfa.uga.edu/">Financial Aid</a></li>
	<li><a href="http://international.uga.edu/">International Education</a></li>
	<li><a href="http://honors.uga.edu/">Honors Program</a></li>
	<li><a href="http://www.libs.uga.edu/">Library</a></li>
</ul>
